/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { AdService } from "../ad.service";
import { AdCreateInput } from "./AdCreateInput";
import { Ad } from "./Ad";
import { AdFindManyArgs } from "./AdFindManyArgs";
import { AdWhereUniqueInput } from "./AdWhereUniqueInput";
import { AdUpdateInput } from "./AdUpdateInput";
import { TransactionFindManyArgs } from "../../transaction/base/TransactionFindManyArgs";
import { Transaction } from "../../transaction/base/Transaction";
import { TransactionWhereUniqueInput } from "../../transaction/base/TransactionWhereUniqueInput";
import { AdminPanelFindManyArgs } from "../../adminPanel/base/AdminPanelFindManyArgs";
import { AdminPanel } from "../../adminPanel/base/AdminPanel";
import { AdminPanelWhereUniqueInput } from "../../adminPanel/base/AdminPanelWhereUniqueInput";

export class AdControllerBase {
  constructor(protected readonly service: AdService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Ad })
  async createAd(@common.Body() data: AdCreateInput): Promise<Ad> {
    return await this.service.createAd({
      data: {
        ...data,

        category: data.category
          ? {
              connect: data.category,
            }
          : undefined,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        title: true,
        description: true,
        price: true,

        category: {
          select: {
            id: true,
          },
        },

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Ad] })
  @ApiNestedQuery(AdFindManyArgs)
  async ads(@common.Req() request: Request): Promise<Ad[]> {
    const args = plainToClass(AdFindManyArgs, request.query);
    return this.service.ads({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        title: true,
        description: true,
        price: true,

        category: {
          select: {
            id: true,
          },
        },

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Ad })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async ad(@common.Param() params: AdWhereUniqueInput): Promise<Ad | null> {
    const result = await this.service.ad({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        title: true,
        description: true,
        price: true,

        category: {
          select: {
            id: true,
          },
        },

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Ad })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateAd(
    @common.Param() params: AdWhereUniqueInput,
    @common.Body() data: AdUpdateInput
  ): Promise<Ad | null> {
    try {
      return await this.service.updateAd({
        where: params,
        data: {
          ...data,

          category: data.category
            ? {
                connect: data.category,
              }
            : undefined,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          title: true,
          description: true,
          price: true,

          category: {
            select: {
              id: true,
            },
          },

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Ad })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteAd(
    @common.Param() params: AdWhereUniqueInput
  ): Promise<Ad | null> {
    try {
      return await this.service.deleteAd({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          title: true,
          description: true,
          price: true,

          category: {
            select: {
              id: true,
            },
          },

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/transactions")
  @ApiNestedQuery(TransactionFindManyArgs)
  async findTransactions(
    @common.Req() request: Request,
    @common.Param() params: AdWhereUniqueInput
  ): Promise<Transaction[]> {
    const query = plainToClass(TransactionFindManyArgs, request.query);
    const results = await this.service.findTransactions(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        totalPrice: true,
        status: true,
        buyer: true,
        seller: true,

        ad: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/transactions")
  async connectTransactions(
    @common.Param() params: AdWhereUniqueInput,
    @common.Body() body: TransactionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      transactions: {
        connect: body,
      },
    };
    await this.service.updateAd({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/transactions")
  async updateTransactions(
    @common.Param() params: AdWhereUniqueInput,
    @common.Body() body: TransactionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      transactions: {
        set: body,
      },
    };
    await this.service.updateAd({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/transactions")
  async disconnectTransactions(
    @common.Param() params: AdWhereUniqueInput,
    @common.Body() body: TransactionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      transactions: {
        disconnect: body,
      },
    };
    await this.service.updateAd({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/adminPanels")
  @ApiNestedQuery(AdminPanelFindManyArgs)
  async findAdminPanels(
    @common.Req() request: Request,
    @common.Param() params: AdWhereUniqueInput
  ): Promise<AdminPanel[]> {
    const query = plainToClass(AdminPanelFindManyArgs, request.query);
    const results = await this.service.findAdminPanels(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,

        ad: {
          select: {
            id: true,
          },
        },

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/adminPanels")
  async connectAdminPanels(
    @common.Param() params: AdWhereUniqueInput,
    @common.Body() body: AdminPanelWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      adminPanels: {
        connect: body,
      },
    };
    await this.service.updateAd({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/adminPanels")
  async updateAdminPanels(
    @common.Param() params: AdWhereUniqueInput,
    @common.Body() body: AdminPanelWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      adminPanels: {
        set: body,
      },
    };
    await this.service.updateAd({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/adminPanels")
  async disconnectAdminPanels(
    @common.Param() params: AdWhereUniqueInput,
    @common.Body() body: AdminPanelWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      adminPanels: {
        disconnect: body,
      },
    };
    await this.service.updateAd({
      where: params,
      data,
      select: { id: true },
    });
  }
}
