/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  IsNumber,
  Min,
  Max,
  ValidateNested,
} from "class-validator";
import { CategoryWhereUniqueInput } from "../../category/base/CategoryWhereUniqueInput";
import { Type } from "class-transformer";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import { TransactionCreateNestedManyWithoutAdsInput } from "./TransactionCreateNestedManyWithoutAdsInput";
import { AdminPanelCreateNestedManyWithoutAdsInput } from "./AdminPanelCreateNestedManyWithoutAdsInput";

@InputType()
class AdCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  price?: number | null;

  @ApiProperty({
    required: false,
    type: () => CategoryWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CategoryWhereUniqueInput)
  @IsOptional()
  @Field(() => CategoryWhereUniqueInput, {
    nullable: true,
  })
  category?: CategoryWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => TransactionCreateNestedManyWithoutAdsInput,
  })
  @ValidateNested()
  @Type(() => TransactionCreateNestedManyWithoutAdsInput)
  @IsOptional()
  @Field(() => TransactionCreateNestedManyWithoutAdsInput, {
    nullable: true,
  })
  transactions?: TransactionCreateNestedManyWithoutAdsInput;

  @ApiProperty({
    required: false,
    type: () => AdminPanelCreateNestedManyWithoutAdsInput,
  })
  @ValidateNested()
  @Type(() => AdminPanelCreateNestedManyWithoutAdsInput)
  @IsOptional()
  @Field(() => AdminPanelCreateNestedManyWithoutAdsInput, {
    nullable: true,
  })
  adminPanels?: AdminPanelCreateNestedManyWithoutAdsInput;
}

export { AdCreateInput as AdCreateInput };
